### ISSUE TITLE
PIXI import / namespace?

### ISSUE THREAD

**Issue by raould** [mattherman/phaser-typescript-template#1]
Thanks for making this template! A question about PIXI...

api i want to use:
https://phaser.io/docs/2.2.2/PIXI.InvertFilter.html

my code attempt:
```
      this.sprite1.filters = [ new PIXI.InvertFilter() ];
```
compiler error:
src/Level1.ts(6,35): error TS2339: Property 'InvertFilter' does not exist on type 'typeof PIXI'.

**Comment by mattherman** [comment]
Glad you like it, however, this is not really the place to ask questions about Phaser itself.

You should try some of the suggestions on the ["Community" page](http://phaser.io/community) or leaving an issue on the [phaser-ce](https://github.com/photonstorm/phaser-ce) repository.
